# Generated by Django 3.0.3 on 2020-02-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200218_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='file',
            field=models.ImageField(default=1, upload_to='room_photos'),
            preserve_default=False,
        ),
    ]
